version: "3.8"

services:
  web:
    build: .
    command: python /django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=_%p$$c&j3r8pvz77_l-^v+tj$$5_p!o)4(8hq!azkywo5)c1-0o9"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
