" 设置通用选项
set nu
set hlsearch
set autoindent
set cindent
set ts=4
set sw=4
set ruler
set expandtab
colorscheme murphy
set nocp
set showcmd
syntax on
filetype on
filetype plugin on
set nobackup
set undofile
set undodir=~/.vim/undodir

" 设置leader全局和本地值
let mapleader='\'
let maplocalleader=','

" 插件配置管理
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

Plug 'scrooloose/nerdtree'
call plug#end()

if !isdirectory(&undodir)
  call mkdir(&undodir, 'p', 0700)
endif

