" 设置通用选项
set nocp
set number
set hlsearch
set autoindent
set cindent
set ts=4
set sw=4
set bs=indent,eol,start
set ruler
set expandtab
colorscheme murphy
set showcmd
syntax on
filetype on
filetype plugin on
set nobackup
set encoding=utf-8

" 设置leader全局和本地值
let mapleader='\'
let maplocalleader=','

" 插件配置管理
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

Plug 'scrooloose/nerdtree'
call plug#end()

