user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;
    limit_req_zone $binary_remote_addr zone=sec_link:10m rate=100r/s;
    log_format log_link '$remote_addr - $secure_link [$time_local] "$request" '
                        '$status $body_bytes_sent $uri';
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80;
        listen       [::]:80;
        server_name  _;
        root         /usr/share/nginx/html;
        include /etc/nginx/default.d/*.conf;

        error_page 404 /404.html;
        location = /404.html {
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }

        location /files/ {
            limit_req zone=sec_link burst=20;
            access_log /var/log/nginx/secure_link.log log_link;
            secure_link $arg_s,$arg_ts;
            secure_link_md5 "$secure_link_expires$uri dev_secret_202607";

            if ($secure_link = "") {
                return 403 "Invalid Signature";
            }

            if ($secure_link = "0") {
                return 410 "Link Expired";
            }

            return 200 "Access OK";
        }
    }
}

