# Profile配置
#spring.profiles.active=xxx

# Server配置
server.port=8080

# Banner的配置
spring.banner.location=classpath:yybanner.txt

# Logging配置
logging.level.org.springframework=INFO
logging.level.study.ywork.springboot=DEBUG
logging.file=todoapp.log

# H2 Datasource配置
spring.datasource.username=yy
spring.datasource.password=yy123456
spring.datasource.driver-class-name=org.h2.Driver
# 配置存放在$HOME/test目录
#spring.datasource.url=jdbc:h2:~/test
# 配置内存数据库
spring.datasource.url=jdbc:h2:mem:test

# H2 console配置
# 访问路径是 /h2-console
spring.h2.console.enabled=true

# MySQL数据源配置
#spring.datasource.username=springboot
#spring.datasource.password=rocks!
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/testdb

# Mybatis的配置
mybatis.type-aliases-package=study.ywork.springboot.entity

# MongoDB的配置
spring.data.mongodb.host=192.168.56.166
spring.data.mongodb.port=27017
spring.data.mongodb.database=test

# Redis配置
spring.redis.database=0
spring.redis.host=192.168.56.166
spring.redis.port=6379
spring.redis.password=yy2019redis

# Actuator的相关配置
info.app.name=study SpringBoot
info.app.description=yy study spring boot
info.app.version=6.6.6
management.endpoints.web.base-path=/eye

# Flyway的相关配置
spring.flyway.locations=classpath:db/migration/h2
spring.flyway.clean-disabled=true

# JPA相关配置
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
