# 配置资源缓存时间
spring.resources.cache.period=10

# 默认的InternalResourceViewResolver类的JSP配置
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 如果想禁用whitelabel error页面，但又想外部容器处理错误
# 使用如下方法:
# @SpringBootApplication(exclude = ErrorMvcAutoConfiguration.class)
# 如果要在嵌入式容器中运行时禁用它，并且我们不想使用基于容器的错误处理使用如下配置
server.error.whitelabel.enabled=false
server.error.include-stacktrace=always
server.error.path=/custom-error

# ViewResolver相关配置
spring.thymeleaf.view-names=thymeleaf*
spring.freemarker.view-names=ftl*
spring.groovy.template.view-names=groovy*
