---
- name: 安装httpd后重启服务
  hosts: webservers
  become: yes
  gather_facts: false
  tasks:
    - name: Install apache package
      yum:
        name: httpd
        state: present
      notify: Restart_Apache
  handlers:
    - name: Restart_Apache
      service:
        name: httpd
        state: restarted

