# 作者: yy
# 日期: 2020-11-18

export UPDATE_ZSH_DAYS=7
export ZSH=$HOME/.oh-my-zsh
export ZSH_COMPDUMP="$HOME/.yyzshdump"
ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh

# 自定义环境变量，如果已有定义则不做处理
if [[ -z "$YYPROGS" ]]; then
    export YYPROGS="$HOME/yybase/progs"
    export JAVA_HOME=`/usr/libexec/java_home`
    export MAVEN_HOME="$YYPROGS/maven"
    export GRADLE_HOME="$YYPROGS/gradle"
    export CATALINA_HOME="$YYPROGS/tomcat"
    YYPATH="$YYPROGS/bin:$HOME/Library/Python/3.8/bin"
    export PATH="$YYPATH:$PATH"
    unset YYPATH
fi

export LANG=zh_CN.UTF-8
# 打开终端启动tmux
~/yybase/progs/bin/yytmux.sh

